CREATE TABLE products
    (
        name VARCHAR(50),
        img VARCHAR(50),
        producttype VARCHAR(50),
        description VARCHAR(550),
        count int,
        item1  VARCHAR(50),
        item2  VARCHAR(50),
        PRIMARY KEY(name)
    );

//End Products

//Pods

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Flash Pod', '/', 'Pods', 'Flash Pods are consumable Slinger ammo Items in Monster Hunter World (MHW). They are used to inflict the Stun effect on a Monster.', 1, 'Flashbug', 'Pod')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Screamer Pod', '/', 'Pods', 'Screamer Pods are consumable Slinger ammo Items in Monster Hunter World (MHW). They are used to disrupt Monsters that burrow underground.', 1, 'Screamer Sac', 'Pod')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Dung Pod', '/', 'Pods', 'Dung Pods are consumable Slinger ammo Items in Monster Hunter World (MHW). They are used to repel Monsters with an unbearable smell.', 2, 'Rolled Up Dung', 'Pod')

//Meat

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Poisoned Meat', '/', 'Meat', 'Poisoned Meat is a Pouch Item in Monster Hunter World (MHW). Meat items are made from Raw Meat carved from Monsters and they can be brought along on hunts. Some meat items can be placed on the ground to lure Monsters and set up traps.', 2, 'Raw Meat', 'Toadstool')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Tinged Meat', '/', 'Meat', 'Tinged meat is a Pouch Item in Monster Hunter World (MHW). Meat items are made from Raw Meat carved from Monsters and they can be brought along on hunts. Some meat items can be placed on the ground to lure Monsters and set up traps.', 0, 'Raw Meat', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Drugged Meat', '/', 'Meat', 'Drugged Meat is a Pouch Item in Monster Hunter World (MHW). Meat items are made from Raw Meat carved from Monsters and they can be brought along on hunts. Some meat items can be placed on the ground to lure Monsters and set up traps.', 1, 'Raw Meat', 'Sleep Herb')

//Traps

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Pitfall Trap', '/', 'Traps', 'DThe Pitfall Trap is a consumable Pouch Item in Monster Hunter World (MHW). It allows a Hunter to incapacitate a Large Monster for a short time, setting it up for Capture or an opportunity to go on the offensive.', 4, 'Trap Tool', 'Net')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Shock Trap', '/', 'Traps', 'The Shock Trap is a consumable Pouch Item in Monster Hunter World (MHW). It allows a Hunter to incapacitate a Large Monster for a short time, setting it up for Capture or an opportunity to go on the offensive.', 5, 'Trap Tool', 'Thunderbug')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Net', '/', 'Traps', 'This material can be obtained by completing Quests, gathering out on the field, or defeating Monsters.', 3, 'Ivy', 'Spiderweb')

//Knives

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Paralysis Knife', '/', 'Knives', 'Paralysis Knife is Slinger Ammo in Monster Hunter World (MHW).', 3, 'Throwing Knife', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Sleep Knife', '/', 'Knives', 'Sleep Knife is Slinger Ammo in Monster Hunter World (MHW).', 3, 'Throwing Knife', 'Sleep Herb');
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Poison Knife', '/', 'Knives', 'Poison Knife is Slinger Ammo in Monster Hunter World (MHW).', 3, 'Throwing Knife', 'Toadstool')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Tranq Knife', '/', 'Knives', 'Tranq Knife is Slinger Ammo in Monster Hunter World (MHW).', 3, 'Throwing Knife', 'Tranq Bomb')

//Bombs

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Barrel Bomb', '/', 'Bombs', 'Barrel Bombs are consumable Pouch Items in Monster Hunter World (MHW). Bomb items can be placed on the ground and triggered by attacks to deal damage..', 3, 'Small Barrel', 'Fire Herb')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Bounce Bomb', '/', 'Bombs', 'Bounce Bombs are consumable Pouch Items in Monster Hunter World (MHW). Bomb items can be placed on the ground and triggered by attacks to deal damage.', 1, 'Small Barrel', 'Nitoshroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Mega Bounce Bomb', '/', 'Bombs', 'Mega Bounce Bombs are consumable Pouch Items in Monster Hunter World (MHW). Bomb items can be placed on the ground and triggered by attacks to deal damage.', 2, 'Bounce Bomb', 'Nitoshroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Large Barrel Bomb', '/', 'Bombs', 'Large Barrel Bombs are consumable Pouch Items in Monster Hunter World (MHW). Bomb items can be placed on the ground and triggered by attacks to deal damage.', 3, 'Large Barrel', 'Gunpowder')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Smoke Bomb', '/', 'Bombs', 'Smoke Bomb is a consumable Item in Monster Hunter World (MHW). These useful items can be crafted from materials gathered in the field and brought along on hunts.', '0', 'Smokenut', 'Ivy')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Poison Smoke Bomb', '/', 'Bombs', 'Poison Smoke Bomb is an Item in Monster Hunter World (MHW). It allows a Hunter to trigger Poison effects on Monsters.', 1, 'Smokenut', 'Toadstool')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Tranq Bomb', '/', 'Bombs', 'Tranq Bomb is a consumable Pouch Item in Monster Hunter World (MHW). It allows Hunters to capture a Monster once they have weakened and trapped it.', 2, 'Sleep Herb', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Mega Barrel Bomb', '/', 'Bombs', 'Mega Barrel Bombs are consumable Pouch Items in Monster Hunter World (MHW). Bomb items can be placed on the ground and triggered by attacks to deal damage.', 1, 'Large Barrel Bomb', 'Devils Blight')

//Ammo

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Dragon Ammo', '/', 'Ammo', 'Dragon Ammo is an Ammo type of Item in Monster Hunter World (MHW).', 1, 'Normal Ammo 1', 'Dragonfell Berry')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Poison Ammo', '/', 'Ammo', 'Poison Ammo is an Ammo type in Monster Hunter World (MHW); it comes in two levels.', 1, 'Normal Ammo 1', 'Toadstool')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Paralysis Ammo', '/', 'Ammo', 'Paralysis Ammo is an Ammo type in Monster Hunter World (MHW); it comes in two levels.', 2, 'Normal Ammo 1', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Tranq Ammo', '/', 'Ammo', 'Tranq Ammo is an Ammo type of Item in Monster Hunter World (MHW). ', 2, 'Normal Ammo 1', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Power Coating', '/', 'Ammo', 'Power Coating is an Item in Monster Hunter World (MHW).', 2, 'Empty Phial', 'Nitoshroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Poison Coating', '/', 'Ammo', 'Poison Coating is an Item in Monster Hunter World (MHW).', 12, 'Empty Phial', 'Toadstool')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Paralysis Coating', '/', 'Ammo', 'Paralysis Coating is an Item in Monster Hunter World (MHW). ', 12, 'Empty Phial', 'Parashroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Sleep Coating', '/', 'Ammo', 'Sleep Coating is an Item in Monster Hunter World (MHW).', 1, 'Empty Phial', 'Sleep Herb')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Blast Coating', '/', 'Ammo', 'Blast Coating is an Item in Monster Hunter World (MHW).', 3, 'Empty Phial', 'Fire Herb')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Water Ammo', '/', 'Ammo', 'Water Ammo is an Ammo type of Item in Monster Hunter World (MHW).', 5, 'Normal Ammo 1', 'Flowfern')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Slicing Ammo', '/', 'Ammo', 'Slicing Ammo is an Ammo type of Item in Monster Hunter World (MHW). When fired from a Bowgun, Slicing Ammo releases a single projectile which sticks to a target, causing a rapid chain of five damage ticks after a short delay. Only Bowguns can make use of Slicing Ammo.', 0, 'Normal Ammo 1', 'Slashberry')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Thunder Ammo', '/', 'Ammo', 'Thunder Ammo is an Ammo type of Item in Monster Hunter World (MHW).', 0, 'Normal Ammo 1', 'Thunderbug')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Freeze Ammo', '/', 'Ammo', 'Freeze Ammo is an Ammo type of Item in Monster Hunter World (MHW).', 0, 'Normal Ammo 1', 'Snow Herb')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Flaming Ammo', '/', 'Ammo', 'Flaming Ammo is an Ammo type of Item in Monster Hunter World (MHW). ', 0, 'Normal Ammo 1', 'Fire Herb')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Sleep Ammo', '/', 'Ammo', 'Sleep Ammo is an Ammo type in Monster Hunter World (MHW); it comes in two levels. When fired from a Bowgun, Sleep Ammo releases a single projectile which deals Sleep buildup damage to a target.', 9, 'Normal Ammo 1', 'Catalyst')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Exhaust Ammo', '/', 'Ammo', 'Exhaust Ammo is an Ammo type in Monster Hunter World (MHW); it comes in two levels. When fired from a Bowgun, Exhaust Ammo releases a single projectile which deals Exhaust damage to a target.', 8, 'Normal Ammo 1', 'Exciteshroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Recover Ammo', '/', 'Ammo', 'Recover Ammo is an Ammo type in Monster Hunter World (MHW); it comes in two levels. When fired from a Bowgun, Recover Ammo releases a single projectile which restores Health to allies.', 7, 'Normal Ammo 1', 'Catalyst')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Demon Ammo', '/', 'Ammo', 'Demon Ammo is a Bowgun Ammo type of Item in Monster Hunter World (MHW). Upon being hit with Demon Ammo by a teammate, a hunters Raw Base damage will be increased by 10.', 6, 'Normal Ammo 1', 'Demondrug')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Armor Ammo', '/', 'Ammo', 'Armor Ammo is a Bowgun Ammo type of Item in Monster Hunter World (MHW).', 5, 'Normal Ammo 1', 'Armorskin')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Wyvern Ammo', '/', 'Ammo', 'Wyvern Ammo is an Ammo type of Item in Monster Hunter World (MHW). When fired from a Bowgun, Wyvern Ammo releases a wide, short-range explosion and a narrow, minor explosion at the end of the barrel after a chargeup period. Only Heavy Bowguns can make use of Wyvern Ammo.', 4, 'Normal Ammo 1', 'Dragonstrike Nut')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Gunpowder', '/', 'Ammo', 'Gunpowder is a Material type of Item in Monster Hunter World (MHW). These useful parts are gathered and collected by Hunters in order to improve their Equipment and performance out in the field.', 4, 'Burst Arowana Scale', 'Fire Herb')

//Potions

INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Potion', '/', 'Potions', 'Potion is a consumable Item in Monster Hunter World (MHW). These useful items can be crafted from materials gathered in the field and brought along on hunts.', 3, 'Herb', 'N/A')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Mega Potion', '/', 'Potions', 'Mega Potion is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 2, 'Potion', 'Honey')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('First Aid Med +', '/', 'Potions', 'First-aid Med+ is an Item in Monster Hunter World (MHW). ', 1, 'First Aid Med', 'Honey')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Antitode', '/', 'Potions', 'Antidote is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 2, 'Antidote Herb', 'N/A')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Herbal Medicine', '/', 'Potions', 'Herbal Medicine is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 3, 'Antidote', 'Blue Mushroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Nutrients', '/', 'Potions', 'Nutrients is a Material Item in Monster Hunter World (MHW). These useful parts are gathered and collected by Hunters in order to improve their equipment and performance out in the field.', 4, 'Bitterbug', 'Blue Mushroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Mega Nutrients', '/', 'Potions', 'Mega Nutrients is a Material Item in Monster Hunter World (MHW). These useful parts are gathered and collected by Hunters in order to improve their equipment and performance out in the field.', 5, 'Nutrients', 'Honey')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Max Potion', '/', 'Potions', 'Max Potion is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 6, 'Mega Nutrients', 'Mandragora')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Catalyst', '/', 'Potions', 'Catalyst is a Material and a Pouch Item in Monster Hunter World (MHW). These useful parts are collected by Hunters to craft new Items, and can be brought along on hunts in the Item Pouch.', 6, 'Bitterbug', 'Honey')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Immunizer', '/', 'Potions', 'Immunizer is a consumable Item in Monster Hunter World (MHW). These useful items can be crafted from materials gathered in the field and brought along on hunts.', 0, 'Catalyst', 'Mandragora')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Ancient Potion', '/', 'Potions', 'Ancient Potion is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 0, 'Nourishing Extract', 'Kelbi Horn')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Lifepowder', '/', 'Potions', 'Lifepowder is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 1, 'Blue Mushroom', 'Godbug')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Herbal Powder', '/', 'Potions', 'Herbal Powder is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 1, 'Herbal Medicine', 'Godbug')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Energy Drink', '/', 'Potions', 'Energy Drink is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 2, 'Honey', 'Nitoshroom')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Dash Juice', '/', 'Potions', 'Dash Juice is a consumable Item in Monster Hunter World (MHW). These useful items can be crafted from materials gathered in the field and brought along on hunts.', 3, 'Catalyst', 'Dash Extract')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Demondrug', '/', 'Potions', 'Demondrug is a Craftable  consumable Item in Monster Hunter World (MHW). These useful items can be crafted with Items gathered in the field and brought along on hunts.', 3, 'Catalyst', 'Might Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Demon Powder', '/', 'Potions', 'Demon Powder is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 1, 'Godbug', 'Might Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Might Pill', '/', 'Potions', 'Might Pill is a Craftable consumable Item in Monster Hunter World (MHW). These useful items can be crafted with Items gathered in the field and brought along on hunts.', 1, 'Immunizer', 'Might Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Armorskin', '/', 'Potions', 'Armorskin is a Craftable consumable Item in Monster Hunter World (MHW). These useful items can be crafted with Items gathered in the field and brought along on hunts.', 0, 'Catalyst', 'Adamant Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Hardshell Powder', '/', 'Potions', 'Hardshell Powder is a consumable Item in Monster Hunter World (MHW). These useful Items can be crafted from materials gathered in the field and brought along on hunts.', 0, 'Godbug', 'Adamant Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Adamant Pill', '/', 'Potions', 'Adamant Pill is a Craftable consumable Item in Monster Hunter World (MHW). These useful items can be crafted with Items gathered in the field and brought along on hunts.', 2, 'Immunizer', 'Adamant Seed')
INSERT INTO`products`(`name`, `img`, `producttype`, `description`, `count`, `item1`, `item2`) VALUES('Farcaster', '/', 'Potions', 'Farcaster is a consumable Item in Monster Hunter World (MHW). These useful items can be crafted from materials gathered in the field and brought along on hunts.', 2, 'Smokenut', 'Exciteshroom')
